version: "3.9"
services:
  client:
    image : tamilarasug/feedback-client
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8091:3000
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 150M
      replicas: 2
      update_config:
        parallelism: 1
        delay: 1m
        failure_action: rollback
networks:
  default:
    name: swarm-server
    external: true
