#!/usr/bin/bash

LOG_FILE="DIR/execpipe.log"

while true
do
  while read command
  do
    case $command in 
      "updateScript server") echo "Command recieved to update server on `date`" >> $LOG_FILE && eval "$command"
        ;;
      "updateScript client") echo "Command recieved to update client on `date`" >> $LOG_FILE && eval "$command"
        ;;
      "updateScript server client") echo "Command recieved to update server and client on `date`" >> $LOG_FILE && eval "$command"
        ;;
      "updateScript client server") echo "Command recieved to update client and server on `date`" >> $LOG_FILE && eval "$command"
        ;;
      *) echo "Invalid Command Recieved: $command on `date`" >> $LOG_FILE 
    esac
  done < DIR/server/mypipe
done
