#!/usr/bin/bash

while true
do
  while read command
  do
    case $command in 
      "updateScript server") eval "$command"
        ;;
      "updateScript client") eval "$command"
        ;;
      "updateScript server client") eval "$command"
        ;;
      "updateScript client server") eval "$command"
        ;;
      *) echo "Invalid Command Recieved: $command at `date`"
    esac
  done < DIR/server/mypipe
done
