version: "3.9"
services:
  server:
    image : tamilarasug/feedback-server
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:5000
    env_file:
      .env
    volumes:
      - ./log.txt:/app/log.txt
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 150M
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 1m
networks:
  default:
    name: swarm-server
    external: true
